### ISSUE TITLE
How does it compare it OpenVPN?

### ISSUE THREAD

**Issue by vi** [twitchyliquid64/subnet#6]
Is it just Yet Another VPN or something special? I see it gaining stars on Github, but don't see what is the point from cursory glance over the README.

The repository description (now just "Simple VPN") should mention the distinguishing characteristic of the project, also there should be some comparison with other competiting project in README.

**Comment by twitchyliquid64** [comment]
I've updated the description.

Subnet is different in that it implements the MVP for a VPN in a very small amount of code, and uses TLS primitives to authenticate client & server (along with providing encryption, of course). This is easy to audit, understand, and run.

Subnet is performant enough for personal use but due to design decisions is unable to fully utilise your link (TCP-in-TCP problem). I can push about 16-17mbps through subnet when my ISP connection can do 20mbps otherwise. If you are after raw performance, other VPN software will win there.

Apart from that, its Yet Another VPN.
